// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBundlePackage = "bundle_package"

// BundlePackage mapped from table <bundle_package>
type BundlePackage struct {
	ID        int32      `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	BundleID  int32      `gorm:"column:bundle_id;type:int(11);not null;uniqueIndex:bundle_id_package_id,priority:1" json:"bundle_id" form:"bundle_id"`
	PackageID int32      `gorm:"column:package_id;type:int(11);not null;uniqueIndex:bundle_id_package_id,priority:2;index:package_id,priority:1" json:"package_id" form:"package_id"`
	DateStart int32 	 `gorm:"column:date_start;" json:"date_start" form:"date_start"`
	DateEnd   int32 	 `gorm:"column:date_end;" json:"date_end" form:"date_end"`
	Starte    string 	 `json:"starte"`
	Count      int       `json:"count_to"`
	Ende       string 	 `json:"ende"`
	CreatedAt *int32     `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt *int32     `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy *int32     `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
	UpdatedBy *int32     `gorm:"column:updated_by;type:int(11);index:updated_by,priority:1" json:"updated_by"`
	Package               Package `gorm:"foreignkey:PackageID" json:"Package"`
	Bundle               Bundle `gorm:"foreignkey:BundleID" json:"Bundle"`
}

type InputBundlePackage struct {
	ID        int32      `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	BundleID  int32      `gorm:"column:bundle_id;type:int(11);not null;uniqueIndex:bundle_id_package_id,priority:1" json:"bundle_id" form:"bundle_id"`
	PackageID int32      `gorm:"column:package_id;type:int(11);not null;uniqueIndex:bundle_id_package_id,priority:2;index:package_id,priority:1" json:"package_id" form:"package_id"`
	DateStart int32      `gorm:"column:date_start;" json:"date_start" form:"date_start"`
	DateEnd   int32      `gorm:"column:date_end;" json:"date_end" form:"date_end"`
	CreatedAt *int32     `gorm:"column:created_at;type:int(11)" json:"created_at"`
	CreatedBy int32     `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
}


// TableName BundlePackage's table name
func (*BundlePackage) TableName() string {
	return TableNameBundlePackage
}
func (*InputBundlePackage) TableName() string {
	return TableNameBundlePackage
}
func (i *InputBundlePackage) BeforeCreate(scope *gorm.DB) error {
    now := int32(time.Now().UTC().Unix())
    i.CreatedAt = &now
    return nil
}

