// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBundle = "bundle"

// Bundle mapped from table <bundle>
type Bundle struct {
	ID          int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name        string  `gorm:"column:name;type:varchar(255);not null" json:"name" form:"name"`
	Description string `gorm:"column:description;type:text" json:"description" form:"description"`
	Price       int32   `gorm:"column:price;type:int(11);not null" json:"price" form:"price"`
	IsActive    int32  `gorm:"column:is_active;type:int(11);default:1" json:"is_active"`
	IsPublic    int32  `gorm:"column:is_public;type:int(11);default:1" json:"is_public" form:"is_public"`
	Type        int32   `gorm:"column:type;type:int(11);not null" json:"type"`
	CreatedAt   *int32  `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt   *int32  `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy   *int32  `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
	UpdatedBy   *int32  `gorm:"column:updated_by;type:int(11);index:updated_by,priority:1" json:"updated_by"`
}

type InputBundle struct {
	ID          int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name        string  `gorm:"column:name;type:varchar(255);not null" json:"name" form:"name"`
	Description *string `gorm:"column:description;type:text" json:"description" form:"description"`
	Price       *int32   `gorm:"column:price;type:int(11)" json:"price" form:"price"`
	Type        int32   `gorm:"column:type;type:int(11);not null" json:"type" form:"type"`
	IsActive    *int32  `gorm:"column:is_active;type:int(11);default:1" json:"is_active" form:"is_active"`
	IsPublic    *int32  `gorm:"column:is_public;type:int(11);default:1" json:"is_public" form:"is_public"`
	CreatedAt   int32  `gorm:"column:created_at;type:int(11);autoCreateTime;loc:UTC" json:"created_at"`
	CreatedBy   int32  `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
}


type BundleSelect struct {
	ID          int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name        string  `gorm:"column:name;type:varchar(255);not null" json:"text"`
}

type BundlePrice struct {
Price       int32   `gorm:"column:price;type:int(11);not null" json:"price"`
}

// TableName Bundle's table name
func (*Bundle) TableName() string {
	return TableNameBundle
}

func (*InputBundle) TableName() string {
	return TableNameBundle
}

func (*BundleSelect) TableName() string {
	return TableNameBundle
}


func (*BundlePrice) TableName() string {
	return TableNameBundle
}

func (i *Bundle) BeforeCreate(scope *gorm.DB) error {
    now := int32(time.Now().UTC().Unix())
    i.CreatedAt = &now
    return nil
}