// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBundleMaterial = "bundle_material"

// BundleMaterial mapped from table <bundle_material>
type BundleMaterial struct {
	ID         int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	BundleID   int32  `gorm:"column:bundle_id;type:int(11);not null;index:bundle_id,priority:1" json:"bundle_id"`
	MaterialID int32  `gorm:"column:material_id;type:int(11);not null;index:material_id,priority:1" json:"material_id"`
	CreatedAt  *int32 `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt  *int32 `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy  *int32 `gorm:"column:created_by;type:int(11)" json:"created_by"`
	UpdatedBy  *int32 `gorm:"column:updated_by;type:int(11)" json:"updated_by"`
	Material   Material `gorm:"foreignkey:MaterialID" json:"Material"`
	Bundle    Bundle `gorm:"foreignkey:BundleID" json:"Bundle"`

}

type InputBundleMaterial struct {
	BundleID   int32  `gorm:"column:bundle_id;type:int(11);not null;index:bundle_id,priority:1" json:"bundle_id" form:"bundle_id"`
	MaterialID int32  `gorm:"column:material_id;type:int(11);not null;index:material_id,priority:1" json:"material_id" form:"material_id"`
	CreatedAt  *int32 `gorm:"column:created_at;type:int(11)" json:"created_at"`
	CreatedBy  *int32 `gorm:"column:created_by;type:int(11)" json:"created_by"`
}


// TableName BundleMaterial's table name
func (*BundleMaterial) TableName() string {
	return TableNameBundleMaterial
}

func (*InputBundleMaterial) TableName() string {
	return TableNameBundleMaterial
}


func (i *InputBundleMaterial) BeforeCreate(scope *gorm.DB) error {
    now := int32(time.Now().UTC().Unix())
    i.CreatedAt = &now
    return nil
}
