// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExamQuestion = "exam_question"

// ExamQuestion mapped from table <exam_question>
type ExamQuestion struct {
	ID         int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	ExamID     int32  `gorm:"column:exam_id;type:int(11);not null;index:exam_id,priority:1" json:"exam_id"`
	QuestionID int32  `gorm:"column:question_id;type:int(11);not null;index:question_id,priority:1" json:"question_id"`
	OptionID   int32  `gorm:"column:option_id;type:int(11);not null;index:option_id,priority:1" json:"option_id"`
	CreatedAt  *int32 `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt  *int32 `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy  *int32 `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
	UpdatedBy  *int32 `gorm:"column:updated_by;type:int(11);index:updated_by,priority:1" json:"updated_by"`
}

type ExamQuestionData struct {
	ID         int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	ExamID     int32  `gorm:"column:exam_id;type:int(11);not null;index:exam_id,priority:1" json:"exam_id"`
	QuestionID int32  `gorm:"column:question_id;type:int(11);not null;index:question_id,priority:1" json:"question_id"`
	Sequence   *int32 `gorm:"column:sequence;type:int(11)" json:"sequence"`
	UpdatedAtTe string   `json:"updated_at_t"`
	OptionID   int32  `gorm:"column:option_id;type:int(11);not null;index:option_id,priority:1" json:"option_id"`
	CreatedAt  *int32 `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt  *int32 `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy  *int32 `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
	UpdatedBy  *int32 `gorm:"column:updated_by;type:int(11);index:updated_by,priority:1" json:"updated_by"`
	Question   Question `gorm:"foreignkey:QuestionID" json:"Question"`
	Option     Option `gorm:"foreignkey:OptionID" json:"Option"`
}


// TableName ExamQuestion's table name
func (*ExamQuestion) TableName() string {
	return TableNameExamQuestion
}
