// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExam = "exam"

// Exam mapped from table <exam>
type Exam struct {
	ID               int32    `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	PackageID        int32    `gorm:"column:package_id;type:int(11);not null;index:package_id,priority:1" json:"package_id"`
	Name                 *string `json:"name"`
	Phone                *string `json:"phone"`
	Email                *string `json:"email"`
	StartedAtTe string   `json:"started_at_t"`
	EndedAtTe   string   `json:"ended_at_t"`
	OrderID          *int32   `gorm:"column:order_id;type:int(11);index:order_id,priority:1" json:"order_id"`
	StartedAt        int32    `gorm:"column:started_at;type:int(11);not null" json:"started_at"`
	EndedAt          *int32   `gorm:"column:ended_at;type:int(11)" json:"ended_at"`
	ExtraTime        *int32   `gorm:"column:extra_time;type:int(11)" json:"extra_time"`
	ScorePercentaged *float64 `gorm:"column:score_percentaged;type:double" json:"score_percentaged"`
	ScoreSummarized  *float64 `gorm:"column:score_summarized;type:double" json:"score_summarized"`
	CreatedAt        *int32   `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt        *int32   `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy        *int32   `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
	UpdatedBy        *int32   `gorm:"column:updated_by;type:int(11);index:updated_by,priority:1" json:"updated_by"`
	Package               Package `gorm:"foreignkey:PackageID" json:"Package"`
	UserFromCreatedBy    SubUser `gorm:"foreignkey:CreatedBy" json:"UserFromCreatedBy"`
}

type ExamDelete struct {
	ID               int32    `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	PackageID        int32    `gorm:"column:package_id;type:int(11);not null;index:package_id,priority:1" json:"package_id"`
	Name                 *string `json:"name"`
	Phone                *string `json:"phone"`
	Email                *string `json:"email"`
	StartedAtTe string   `json:"started_at_t"`
	EndedAtTe   string   `json:"ended_at_t"`
	OrderID          *int32   `gorm:"column:order_id;type:int(11);index:order_id,priority:1" json:"order_id"`
	StartedAt        int32    `gorm:"column:started_at;type:int(11);not null" json:"started_at"`
	EndedAt          *int32   `gorm:"column:ended_at;type:int(11)" json:"ended_at"`
	ExtraTime        *int32   `gorm:"column:extra_time;type:int(11)" json:"extra_time"`
	ScorePercentaged *float64 `gorm:"column:score_percentaged;type:double" json:"score_percentaged"`
	ScoreSummarized  *float64 `gorm:"column:score_summarized;type:double" json:"score_summarized"`
	CreatedAt        *int32   `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt        *int32   `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy        *int32   `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
	UpdatedBy        *int32   `gorm:"column:updated_by;type:int(11);index:updated_by,priority:1" json:"updated_by"`
}

type SubExam struct {
	ID               int32    `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
}

type ExamQuestionScore struct {
	SumScore    float64 `gorm:"column:sumscore;" json:"sumscore"`
	CountQuestion    float64 `gorm:"column:count_question;" json:"count_question"`
}

// TableName Exam's table name
func (*Exam) TableName() string {
	return TableNameExam
}

func (*SubExam) TableName() string {
	return TableNameExam
}

func (*ExamDelete) TableName() string {
	return TableNameExam
}

