// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMaterial = "material"

// Material mapped from table <material>
type Material struct {
	ID          int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name        string  `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Description string `gorm:"column:description;type:text" json:"description"`
	IsActive    int32  `gorm:"column:is_active;type:int(11);default:1" json:"is_active"` // available to add to classroom
	CreatedAt   *int32  `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt   *int32  `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy   *int32  `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
	UpdatedBy   *int32  `gorm:"column:updated_by;type:int(11);index:updated_by,priority:1" json:"updated_by"`
}

type InputMaterial struct {
	ID          int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name        string  `gorm:"column:name;type:varchar(255);not null" json:"name" form:"name"`
	Description *string `gorm:"column:description;type:text" json:"description" form:"description"`
	IsActive    *int32  `gorm:"column:is_active;type:int(11);default:1" json:"is_active" form:"is_active"` // available to add to classroom
	CreatedAt   *int32  `gorm:"column:created_at;type:int(11)" json:"created_at"`
	CreatedBy   *int32  `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
}

type MaterialSelect struct {
	ID            int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name          string  `gorm:"column:name;type:varchar(255);not null" json:"text"`
}

// TableName Material's table name
func (*Material) TableName() string {
	return TableNameMaterial
}

func (*InputMaterial) TableName() string {
	return TableNameMaterial
}

func (*MaterialSelect) TableName() string {
	return TableNameMaterial
}


func (i *InputMaterial) BeforeCreate(scope *gorm.DB) error {
    now := int32(time.Now().UTC().Unix())
    i.CreatedAt = &now
    return nil
}

