// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOption = "option"

// Option mapped from table <option>
type Option struct {
	ID          int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	QuestionID  int32   `gorm:"column:question_id;type:int(11);not null;index:question_id,priority:1" json:"question_id"`
	Name        string  `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Description *string `gorm:"column:description;type:varchar(255)" json:"description" form:"description"`
	FileImage   *string `gorm:"column:file_image;type:text" json:"file_image"`
	IsTrue      int32   `gorm:"column:is_true;type:int(11);not null" json:"is_true" form:"is_true"`
	CreatedAt   *int32  `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt   int32  `gorm:"column:updated_at;type:int(11);autoCreateTime;loc:UTC" json:"updated_at"`
	CreatedBy   *int32  `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
	UpdatedBy   *int32  `gorm:"column:updated_by;type:int(11);index:updated_by,priority:1" json:"updated_by"`
}

type InputOption struct {
	QuestionID  int32   `gorm:"column:question_id;type:int(11);not null;index:question_id,priority:1" json:"question_id"`
	Name        string  `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Description *string `gorm:"column:description;type:varchar(255)" json:"description" form:"description"`
	FileImage   *string `gorm:"column:file_image;type:text" json:"file_image"`
	IsTrue      *int32   `gorm:"column:is_true;type:int(11);not null" json:"is_true" form:"is_true"`
	CreatedAt   *int32  `gorm:"column:created_at;type:int(11)" json:"created_at"`
}

func (i *Option) BeforeCreate(scope *gorm.DB) error {
    now := int32(time.Now().UTC().Unix())
    i.CreatedAt = &now
    return nil
}

func (i *InputOption) BeforeCreate(scope *gorm.DB) error {
    now := int32(time.Now().UTC().Unix())
    i.CreatedAt = &now
    return nil
}

// TableName Option's table name
func (*Option) TableName() string {
	return TableNameOption
}

func (*InputOption) TableName() string {
	return TableNameOption
}

