// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePresence = "presence"

// Presence mapped from table <presence>
type Presence struct {
	ID        int32 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	MeetingID int32 `gorm:"column:meeting_id;type:int(11);not null;index:meeting_id,priority:1" json:"meeting_id"`
	UserID    int32 `gorm:"column:user_id;type:int(11);not null" json:"user_id"`
	Email     string `json:"email"`
	Start     int32 `gorm:"column:start;type:int(11);not null" json:"start"`
	Starte    string `gorm:"column:start;type:int(11);not null" json:"starte"`
	End       int32 `gorm:"column:end;type:int(11);not null" json:"end"`
	Ende       string `gorm:"column:end;type:int(11);not null" json:"ende"`
	Rate      int32 `gorm:"column:rate;type:int(11);not null" json:"rate"`
	Comment   int32 `gorm:"column:comment;type:int(11);not null" json:"comment"`
	CreatedAt int32 `gorm:"column:created_at;type:int(11);not null" json:"created_at"`
	UpdatedAt int32 `gorm:"column:updated_at;type:int(11);not null" json:"updated_at"`
	CreatedBy int32 `gorm:"column:created_by;type:int(11);not null" json:"created_by"`
	UpdatedBy int32 `gorm:"column:updated_by;type:int(11);not null" json:"updated_by"`
	Meeting   Meeting `gorm:"foreignkey:MeetingID" json:"Meeting"`
	UserFromID           SubUser `gorm:"foreignkey:UserID" json:"UserFromID"`
}

// TableName Presence's table name
func (*Presence) TableName() string {
	return TableNamePresence
}
