// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductIncome = "product_income"

// ProductIncome mapped from table <product_income>
type ProductIncome struct {
	ID        int32 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	ProductID int32 `gorm:"column:product_id;type:int(11);not null" json:"product_id"`
	Stok      int32 `gorm:"column:stok;type:int(11);not null" json:"stok"`
	CreatedAt int32 `gorm:"column:created_at;type:int(11);not null" json:"created_at"`
}

// TableName ProductIncome's table name
func (*ProductIncome) TableName() string {
	return TableNameProductIncome
}
