// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductUser = "product_user"

// ProductUser mapped from table <product_user>
type ProductUser struct {
	ID        int32 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	ProductID int32 `gorm:"column:product_id;type:int(11);not null" json:"product_id"`
	UserID    int32 `gorm:"column:user_id;type:int(11);not null" json:"user_id"`
	User      User `gorm:"foreignkey:UserID" json:"User"`
	Quantity    int32 `gorm:"column:quantity;type:int(11);not null" json:"quantity"`
	PriceNonmember int32  `gorm:"column:price_nonmember;type:int(11);not null" json:"price_nonmember"`
	PriceMember    int32  `gorm:"column:price_member;type:int(11);not null" json:"price_member"`
	Product   Product  `gorm:"foreignkey:ProductID" json:"Product"`
}

type InputProductUser struct {
	ProductID int32 `gorm:"column:product_id;type:int(11);not null" json:"product_id" form:"product_id"`
	UserID    int32 `gorm:"column:user_id;type:int(11);not null" json:"user_id" form:"user_id"`
	Quantity    *int32 `gorm:"column:quantity;type:int(11);not null" json:"quantity" form:"quantity"`
	PriceNonmember int32  `gorm:"column:price_nonmember;type:int(11);not null" json:"price_nonmember"`
	PriceMember    int32  `gorm:"column:price_member;type:int(11);not null" json:"price_member"`
	CreatedAt int32 `gorm:"column:created_at;type:int(11);autoCreateTime;loc:UTC" json:"created_at"`
	UpdatedAt int32 `gorm:"column:updated_at;type:int(11);autoUpdateTime;loc:UTC" json:"updated_at"`
}

// TableName ProductUser's table name
func (*ProductUser) TableName() string {
	return TableNameProductUser
}
func (*InputProductUser) TableName() string {
	return TableNameProductUser
}
