// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReport = "report"

// Report mapped from table <report>
type Report struct {
	ID   int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id" form:"id"`
	Name string `gorm:"column:name;type:varchar(255);not null" json:"name" form:"name"`
	/*
		1=pendapatan usaha
		2=beban usaha
		3=pendapatan diluar usaha
		4 beban diluar usaha
	*/
	CategoriID int32 `gorm:"column:categori_id;type:int(11);not null" json:"categori_id" form:"categori_id"`
	Price      int32 `gorm:"column:price;type:int(11);not null" json:"price" form:"price"`
	CreatedAt  int32 `gorm:"column:created_at;type:int(11);not null" json:"created_at"`
	UpdatedAt  int32 `gorm:"column:updated_at;type:int(11);not null" json:"updated_at"`
	CreatedBy  int32 `gorm:"column:created_by;type:int(11);not null" json:"created_by"`
	UpdatedBy  int32 `gorm:"column:updated_by;type:int(11);not null" json:"updated_by"`
	CreatedAt_t string `gorm:"column:created_at;type:int(11);" json:"created_at_t"`
}

// TableName Report's table name
func (*Report) TableName() string {
	return TableNameReport
}
