// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSection = "section"

// Section mapped from table <section>
type Section struct {
	ID           int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	VersionID    int32  `gorm:"column:version_id;type:int(11);not null;index:version_id,priority:1" json:"version_id" form:"version_id"`
	Sequence     int32  `gorm:"column:sequence;type:int(11);not null" json:"sequence" form:"sequence"`
	Name         string `gorm:"column:name;type:varchar(255);not null" json:"name" form:"name"`
	Duration      int32   `gorm:"column:duration;type:int(11);not null" json:"duration" form:"duration"`
	MinimumScore int32  `gorm:"column:minimum_score;type:int(11);not null" json:"minimum_score" form:"minimum_score"`
	CreatedAt    *int32 `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt    *int32 `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy    *int32 `gorm:"column:created_by;type:int(11)" json:"created_by"`
	UpdatedBy    *int32 `gorm:"column:updated_by;type:int(11)" json:"updated_by"`
	Version      Version `gorm:"foreignkey:VersionID" json:"Version"`

}

type InputSection struct {
	ID           int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	VersionID    int32  `gorm:"column:version_id;type:int(11);not null;index:version_id,priority:1" json:"version_id" form:"version_id"`
	Sequence     int32  `gorm:"column:sequence;type:int(11);not null" json:"sequence" form:"sequence"`
	Duration     *int32   `gorm:"column:duration;type:int(11);null" json:"duration" form:"duration"`
	Name         string `gorm:"column:name;type:varchar(255);not null" json:"name" form:"name"`
	MinimumScore *int32  `gorm:"column:minimum_score;type:int(11);not null" json:"minimum_score" form:"minimum_score"`
	CreatedAt    *int32 `gorm:"column:created_at;type:int(11)" json:"created_at"`
	CreatedBy    int32 `gorm:"column:created_by;type:int(11)" json:"created_by"`

}

type SequenceSection struct {
	ID           int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
}

func (i *InputSection) BeforeCreate(scope *gorm.DB) error {
    now := int32(time.Now().UTC().Unix())
    i.CreatedAt = &now
    return nil
}

// TableName Section's table name
func (*Section) TableName() string {
	return TableNameSection
}
func (*InputSection) TableName() string {
	return TableNameSection
}
func (*SequenceSection) TableName() string {
	return TableNameSection
}


