// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVersion = "version"

// Version mapped from table <version>
type Version struct {
	ID        int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name      string `gorm:"column:name;type:varchar(225);not null" json:"name" form:"name"`
	Type        int32  `gorm:"column:type;type:int(11)" json:"type" form:"type"`
	IsActive   int32  `gorm:"column:is_active;type:int(11)" json:"is_active" form:"is_active"`
	CreatedAt int32 `gorm:"column:created_at;type:int(11);autoCreateTime;loc:UTC" json:"created_at"`
	UpdatedAt int32 `gorm:"column:updated_at;type:int(11);autoUpdateTime;loc:UTC" json:"updated_at"`
	CreatedBy *int32 `gorm:"column:created_by;type:int(11)" json:"created_by"`
	UpdatedBy *int32 `gorm:"column:updated_by;type:int(11)" json:"updated_by"`
	Section    []Section `gorm:"foreignkey:VersionID" json:"Section"`
}



type VersionSelect struct {
	ID            int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name          string  `gorm:"column:name;type:varchar(255);not null" json:"text"`
}

// TableName Version's table name
func (*Version) TableName() string {
	return TableNameVersion
}


func (*VersionSelect) TableName() string {
	return TableNameVersion
}

